const express = require("express");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execSync } = require("child_process");

const app = express();
const PORT = process.env.PORT || 3000;
const HISTORY_PATH = path.join(__dirname, "history.json");
const PLANS_PATH = path.join(__dirname, "plans.json");

app.use(express.json({ limit: "1mb" }));
app.use(express.static(path.join(__dirname, "public")));

function safeName(input) {
  return (input || "feature")
    .toLowerCase()
    .replace(/[^a-z0-9-_ ]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 64) || "feature";
}

function ensureDir(target) {
  fs.mkdirSync(target, { recursive: true });
}

function writeFile(filePath, content) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, "utf8");
}

function upsertFile(filePath, content) {
  ensureDir(path.dirname(filePath));
  if (!fs.existsSync(filePath)) fs.writeFileSync(filePath, content, "utf8");
}

function classNameFromFeature(feature) {
  return feature
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function shortPreview(content) {
  const text = content || "";
  const lines = text.split("\n").slice(0, 12).join("\n");
  return lines.length > 700 ? `${lines.slice(0, 700)}...` : lines;
}

function projectKeyFromRoot(root) {
  return Buffer.from(path.resolve(root)).toString("base64");
}

function getHistory() {
  if (!fs.existsSync(HISTORY_PATH)) return [];
  try {
    const parsed = JSON.parse(fs.readFileSync(HISTORY_PATH, "utf8"));
    return Array.isArray(parsed) ? parsed : [];
  } catch (_error) {
    return [];
  }
}

function pushHistory(entry) {
  const current = getHistory();
  writeFile(HISTORY_PATH, JSON.stringify([entry, ...current].slice(0, 100), null, 2) + "\n");
}

function getPlans() {
  if (!fs.existsSync(PLANS_PATH)) return {};
  try {
    const parsed = JSON.parse(fs.readFileSync(PLANS_PATH, "utf8"));
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch (_error) {
    return {};
  }
}

function savePlans(plans) {
  writeFile(PLANS_PATH, JSON.stringify(plans, null, 2) + "\n");
}

function createPlan(root, pkg, featureClass, filePlan, registryPlan, metadata) {
  const planId = `plan_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`;
  const plans = getPlans();
  plans[planId] = {
    createdAt: new Date().toISOString(),
    root,
    pkg,
    featureClass,
    metadata,
    files: filePlan.map((f, i) => ({
      id: `file_${i + 1}`,
      path: f.path,
      content: f.content,
    })),
    registry: {
      id: "registry_1",
      ...registryPlan,
    },
  };
  savePlans(plans);
  return planId;
}

function createProjectSkeleton(root, info) {
  const { modId, pkg, mcVersion, neoForgeVersion, createVersion, aeronauticsModId } = info;
  const javaRoot = path.join(root, "src", "main", "java", ...pkg.split("."));
  const resourcesRoot = path.join(root, "src", "main", "resources");
  const packagePath = pkg.replace(/\./g, "/");

  upsertFile(
    path.join(root, "settings.gradle"),
    `pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases" }
    }
}

rootProject.name = "${modId}"
`,
  );
  upsertFile(
    path.join(root, "gradle.properties"),
    `org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
minecraft_version=${mcVersion}
neo_version=${neoForgeVersion}
create_version=${createVersion}
mod_id=${modId}
mod_name=${modId}
mod_group_id=${pkg}
mod_version=0.1.0
`,
  );
  upsertFile(
    path.join(root, "build.gradle"),
    `plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.0.165'
}

group = project.mod_group_id
version = project.mod_version

repositories {
    mavenCentral()
    maven { url = "https://maven.createmod.net" }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

dependencies {
    implementation "net.neoforged:neoforge:\${neo_version}"
    implementation "com.simibubi.create:create-\${minecraft_version}:\${create_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
`,
  );
  upsertFile(
    path.join(root, "README.md"),
    `# ${modId}

Create addon project generated by Feature UI.
- Minecraft: ${mcVersion}
- NeoForge: ${neoForgeVersion}
- Create: ${createVersion}
- Aeronautics compatibility: optional with mod id \`${aeronauticsModId}\`
`,
  );
  upsertFile(
    path.join(javaRoot, "FeatureRegistry.java"),
    `package ${pkg};

public final class FeatureRegistry {
    private FeatureRegistry() {}

    public static void registerAll() {
        // Generated features are called here.
    }
}
`,
  );
  upsertFile(
    path.join(javaRoot, "CreateAddonMod.java"),
    `package ${pkg};

import net.neoforged.fml.common.Mod;

@Mod("${modId}")
public class CreateAddonMod {
    public CreateAddonMod() {
        FeatureRegistry.registerAll();
    }
}
`,
  );
  upsertFile(
    path.join(resourcesRoot, "META-INF", "neoforge.mods.toml"),
    `modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="${modId}"
version="\${file.jarVersion}"
displayName="${modId}"
description='''Generated Create addon mod'''

[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="[20,)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="[${mcVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="create"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
`,
  );
  upsertFile(
    path.join(resourcesRoot, "pack.mcmeta"),
    `{
  "pack": {
    "pack_format": 26,
    "description": "${modId} resources"
  }
}
`,
  );
  ensureDir(path.join(resourcesRoot, "data", modId, "recipes"));
  ensureDir(path.join(resourcesRoot, "data", modId, "tags", "items"));
  ensureDir(path.join(resourcesRoot, "assets", modId, "lang"));
  upsertFile(path.join(resourcesRoot, "assets", modId, "lang", "en_us.json"), "{}\n");
  upsertFile(path.join(resourcesRoot, "application.properties"), `aeronautics.modid=${aeronauticsModId}\n`);
  upsertFile(path.join(root, ".feature-ui.json"), JSON.stringify({ modId, packagePath }, null, 2) + "\n");
}

function appendFeatureToRegistry(root, pkg, featureClass) {
  const registryPath = path.join(root, "src", "main", "java", ...pkg.split("."), "FeatureRegistry.java");
  if (!fs.existsSync(registryPath)) return { action: "skip", path: registryPath };
  const content = fs.readFileSync(registryPath, "utf8");
  const callLine = `        ${featureClass}Feature.register();`;
  if (content.includes(callLine)) return { action: "unchanged", path: registryPath, preview: callLine };
  const updated = content.replace(
    "    public static void registerAll() {\n        // Generated features are called here.\n    }",
    `    public static void registerAll() {\n        // Generated features are called here.\n${callLine}\n    }`,
  );
  fs.writeFileSync(registryPath, updated, "utf8");
  return { action: "update", path: registryPath, preview: shortPreview(updated) };
}

function planRegistryUpdate(root, pkg, featureClass) {
  const registryPath = path.join(root, "src", "main", "java", ...pkg.split("."), "FeatureRegistry.java");
  if (!fs.existsSync(registryPath)) return { action: "skip", path: registryPath, preview: "Registry does not exist yet." };
  const content = fs.readFileSync(registryPath, "utf8");
  const callLine = `        ${featureClass}Feature.register();`;
  if (content.includes(callLine)) return { action: "unchanged", path: registryPath, preview: callLine };
  const updated = content.replace(
    "    public static void registerAll() {\n        // Generated features are called here.\n    }",
    `    public static void registerAll() {\n        // Generated features are called here.\n${callLine}\n    }`,
  );
  return { action: "update", path: registryPath, preview: shortPreview(updated) };
}

function applyWritePlan(writePlan, dryRun) {
  return writePlan.map((file) => {
    const exists = fs.existsSync(file.path);
    if (!dryRun) writeFile(file.path, file.content);
    return {
      path: file.path,
      action: exists ? "update" : "create",
      preview: shortPreview(file.content),
    };
  });
}

function runProjectTest(projectRoot, command) {
  const defaultCommand = process.platform === "win32" ? "gradlew.bat compileJava" : "./gradlew compileJava";
  const cmd = (command && command.trim()) || defaultCommand;
  try {
    const stdout = execSync(cmd, {
      cwd: projectRoot,
      stdio: "pipe",
      encoding: "utf8",
      shell: true,
      timeout: 180000,
    });
    return { ok: true, command: cmd, output: shortPreview(stdout || "compileJava passed") };
  } catch (error) {
    const out = `${error.stdout || ""}\n${error.stderr || ""}`.trim();
    return { ok: false, command: cmd, output: shortPreview(out || error.message || "Test command failed") };
  }
}

function applyOneChangeWithRollback(change, root, testCommand) {
  const existed = fs.existsSync(change.path);
  const previous = existed ? fs.readFileSync(change.path, "utf8") : null;
  writeFile(change.path, change.content);
  const testResult = runProjectTest(root, testCommand);
  if (testResult.ok) {
    return { kept: true, testResult };
  }
  if (existed) {
    writeFile(change.path, previous);
  } else if (fs.existsSync(change.path)) {
    fs.unlinkSync(change.path);
  }
  return { kept: false, testResult };
}

function packageFromContent(content) {
  const match = (content || "").match(/package\s+([a-zA-Z0-9_.]+)\s*;/);
  return match ? match[1] : "com.example";
}

function classFromFilename(filePath) {
  return path.basename(filePath, ".java");
}

function buildRetryContent(filePath, originalContent) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === ".java") {
    const pkg = packageFromContent(originalContent);
    const cls = classFromFilename(filePath);
    if (cls.endsWith("Feature")) {
      return `package ${pkg};

public final class ${cls} {
    private ${cls}() {}
    public static void register() {}
}
`;
    }
    if (cls.endsWith("Compat")) {
      return `package ${pkg};

public final class ${cls} {
    private ${cls}() {}
    public static void register() {}
}
`;
    }
    if (cls.endsWith("Spec")) {
      return `package ${pkg};

public record ${cls}(String note) {}
`;
    }
    return `package ${pkg};

public final class ${cls} {}
`;
  }
  if (ext === ".json") {
    try {
      JSON.parse(originalContent);
      return originalContent;
    } catch (_error) {
      return "{\n  \"replace\": false,\n  \"values\": []\n}\n";
    }
  }
  return originalContent;
}

function isTooComplexForSafeRetry(filePath, content, failureOutput) {
  const text = content || "";
  const failure = failureOutput || "";
  const isJava = path.extname(filePath).toLowerCase() === ".java";
  const lineCount = text.split("\n").length;
  const hasManyMethods = (text.match(/\b(public|private|protected)\b/g) || []).length > 10;
  const advancedSignals =
    /generic|extends|implements|lambda|stream|mixin|reflection|ClassNotFound|NoSuchMethod/i.test(
      `${text}\n${failure}`,
    );
  if (!isJava) return false;
  if (lineCount > 220) return true;
  if (hasManyMethods && advancedSignals) return true;
  if (advancedSignals && lineCount > 120) return true;
  return false;
}

function complexityRecommendation(filePath) {
  return `Aborted retry for ${filePath}: complexity/risk is too high for safe automatic fallback.
Recommended next step: use Cursor manually on this file with the compile error output, or split the feature into smaller units and retry per unit.`;
}

function aiRetryNarrative(featureTitle, retryApplied, retryFailed) {
  const successLines = retryApplied.map((x) => `- ${x.path}: retry patch compiled`).join("\n");
  const failLines = retryFailed.map((x) => `- ${x.path}: ${x.test.output}`).join("\n");
  return `Retry report for "${featureTitle}"

Retried and fixed: ${retryApplied.length}
Still failing: ${retryFailed.length}

Retry fixes that worked:
${successLines || "- none"}

Still failing after fallback retries:
${failLines || "- none"}

Ask AI to deeply fix only the remaining failing files using these compiler errors.`;
}

function implementFeature(input) {
  const modId = safeName(input.modId || "customcreateaddon").replace(/-/g, "_");
  const pkg = (input.basePackage || "com.taha.customcreate").replace(/[^a-zA-Z0-9_.]/g, "");
  const feature = safeName(input.featureTitle);
  const featureClass = classNameFromFeature(feature);
  const mcVersion = input.minecraftVersion || "1.20.1";
  const neoForgeVersion = input.neoForgeVersion || "20.6.130";
  const createVersion = input.createVersion || "LATEST";
  const aeronauticsModId = input.aeronauticsModId || "create_aeronautics";
  const dryRun = Boolean(input.dryRun);
  const root = input.projectPath ? path.resolve(input.projectPath) : path.join(__dirname, "generated-projects", modId);
  const javaRoot = path.join(root, "src", "main", "java", ...pkg.split("."));
  const resourcesRoot = path.join(root, "src", "main", "resources");

  createProjectSkeleton(root, { modId, pkg, mcVersion, neoForgeVersion, createVersion, aeronauticsModId });

  const writePlan = [
    {
      path: path.join(javaRoot, "FeatureSpec.java"),
      content: `package ${pkg};

public record FeatureSpec(
    String title,
    String requestedBehavior,
    String compatibilityNotes
) {}
`,
    },
    {
      path: path.join(javaRoot, `${featureClass}FeatureSpec.java`),
      content: `package ${pkg};

public record ${featureClass}FeatureSpec(
    String title, String requestedBehavior, String compatibilityNotes
) {}
`,
    },
    {
      path: path.join(javaRoot, `${featureClass}Feature.java`),
      content: `package ${pkg};

import net.neoforged.fml.ModList;

public final class ${featureClass}Feature {
    private static final String AERONAUTICS_MOD_ID = "${aeronauticsModId}";
    private ${featureClass}Feature() {}

    public static void register() {
        registerCore();
        if (ModList.get().isLoaded(AERONAUTICS_MOD_ID)) {
            ${featureClass}AeronauticsCompat.register();
        }
    }

    private static void registerCore() {
        // ${input.featureSummary || "feature behavior"}
    }
}
`,
    },
    {
      path: path.join(javaRoot, `${featureClass}AeronauticsCompat.java`),
      content: `package ${pkg};

public final class ${featureClass}AeronauticsCompat {
    private ${featureClass}AeronauticsCompat() {}

    public static void register() {
        // Aeronautics-specific hooks live here.
    }
}
`,
    },
    {
      path: path.join(resourcesRoot, "data", modId, "tags", "items", "aeronautics_compatible_inputs.json"),
      content: `{
  "replace": false,
  "values": []
}
`,
    },
    {
      path: path.join(resourcesRoot, "data", modId, "recipes", `${feature}.json`),
      content: `{
  "type": "minecraft:crafting_shaped",
  "pattern": [" A ", " B ", " C "],
  "key": {
    "A": { "tag": "${modId}:aeronautics_compatible_inputs" },
    "B": { "item": "minecraft:iron_ingot" },
    "C": { "item": "minecraft:redstone" }
  },
  "result": { "item": "${modId}:${feature}" }
}
`,
    },
  ];

  const files = applyWritePlan(writePlan, dryRun);
  const registryPreview = planRegistryUpdate(root, pkg, featureClass);
  const registryChange = dryRun
    ? planRegistryUpdate(root, pkg, featureClass)
    : appendFeatureToRegistry(root, pkg, featureClass);
  const planId = createPlan(root, pkg, featureClass, writePlan, registryPreview, {
    modId,
    pkg,
    mcVersion,
    neoForgeVersion,
    createVersion,
    aeronauticsModId,
    featureTitle: input.featureTitle,
    featureSummary: input.featureSummary,
  });

  return {
    root,
    files,
    registryChange,
    dryRun,
    featureClass,
    planId,
    metadata: { modId, pkg, mcVersion, neoForgeVersion, createVersion, aeronauticsModId },
  };
}

app.post("/api/generate-feature", (req, res) => {
  const body = req.body || {};
  if (!body.featureTitle || !body.featureSummary) {
    return res.status(400).json({ error: "featureTitle and featureSummary are required." });
  }
  try {
    const result = implementFeature(body);
    const projectKey = projectKeyFromRoot(result.root);
    pushHistory({
      timestamp: new Date().toISOString(),
      featureTitle: body.featureTitle,
      summary: body.featureSummary,
      projectPath: result.root,
      projectKey,
      dryRun: result.dryRun,
      featureClass: result.featureClass,
      changeCount: result.files.length + 1,
    });
    return res.json({
      ok: true,
      outputPath: result.root,
      files: result.files,
      registryChange: result.registryChange,
      dryRun: result.dryRun,
      planId: result.planId,
      projectKey,
      metadata: result.metadata,
    });
  } catch (error) {
    return res.status(500).json({ ok: false, error: error.message || "Unknown generation failure." });
  }
});

app.post("/api/apply-selected", (req, res) => {
  const { planId, selectedIds, testCommand, projectKey } = req.body || {};
  if (!planId || !Array.isArray(selectedIds)) {
    return res.status(400).json({ ok: false, error: "planId and selectedIds are required." });
  }
  const plans = getPlans();
  const plan = plans[planId];
  if (!plan) {
    return res.status(404).json({ ok: false, error: "Plan not found. Generate again." });
  }
  const actualProjectKey = projectKeyFromRoot(plan.root);
  if (projectKey && projectKey !== actualProjectKey) {
    return res.status(409).json({
      ok: false,
      error: "Project mismatch. Regenerate or use the matching project plan.",
    });
  }

  const selectedSet = new Set(selectedIds);
  const applied = [];
  const failed = [];
  const skipped = [];

  for (const file of plan.files) {
    if (!selectedSet.has(file.id)) {
      skipped.push({ id: file.id, path: file.path, reason: "Not selected" });
      continue;
    }
    const result = applyOneChangeWithRollback(file, plan.root, testCommand);
    if (result.kept) {
      applied.push({ id: file.id, path: file.path, test: result.testResult });
    } else {
      failed.push({ id: file.id, path: file.path, test: result.testResult });
    }
  }

  let registryApplied = null;
  if (selectedSet.has(plan.registry.id)) {
    const registryChange = {
      path: plan.registry.path,
      content:
        plan.registry.action === "update" && plan.registry.preview
          ? fs.readFileSync(plan.registry.path, "utf8").replace(
              "    public static void registerAll() {\n        // Generated features are called here.\n    }",
              `    public static void registerAll() {\n        // Generated features are called here.\n        ${plan.featureClass}Feature.register();\n    }`,
            )
          : null,
    };
    if (registryChange.content) {
      const result = applyOneChangeWithRollback(registryChange, plan.root, testCommand);
      registryApplied = {
        id: plan.registry.id,
        path: plan.registry.path,
        kept: result.kept,
        test: result.testResult,
      };
      if (!result.kept) {
        failed.push({
          id: plan.registry.id,
          path: plan.registry.path,
          test: result.testResult,
        });
      }
    }
  } else {
    skipped.push({ id: plan.registry.id, path: plan.registry.path, reason: "Not selected" });
  }

  const failureLines = failed.map((f) => `- ${f.path}: ${f.test.output}`).join("\n");
  const skippedLines = skipped.map((s) => `- ${s.path}: ${s.reason}`).join("\n");
  const aiReport = `Feature apply report for "${plan.metadata.featureTitle}"\n\nApplied successfully: ${applied.length}\nFailed and rolled back: ${failed.length}\nSkipped: ${skipped.length}\n\nFailures:\n${failureLines || "- none"}\n\nSkipped:\n${skippedLines || "- none"}\n\nUse this to generate fixes for failed files only.`;

  pushHistory({
    timestamp: new Date().toISOString(),
    featureTitle: plan.metadata.featureTitle,
    summary: plan.metadata.featureSummary,
    projectPath: plan.root,
    projectKey: actualProjectKey,
    dryRun: false,
    featureClass: plan.featureClass,
    changeCount: applied.length + failed.length + skipped.length,
    status: failed.length > 0 ? "partial" : "success",
  });

  return res.json({
    ok: true,
    projectPath: plan.root,
    applied,
    failed,
    skipped,
    registryApplied,
    aiReport,
  });
});

app.post("/api/retry-failed", (req, res) => {
  const { planId, failed, testCommand, projectKey } = req.body || {};
  if (!planId || !Array.isArray(failed)) {
    return res.status(400).json({ ok: false, error: "planId and failed array are required." });
  }
  const plans = getPlans();
  const plan = plans[planId];
  if (!plan) {
    return res.status(404).json({ ok: false, error: "Plan not found. Generate again." });
  }
  const actualProjectKey = projectKeyFromRoot(plan.root);
  if (projectKey && projectKey !== actualProjectKey) {
    return res.status(409).json({
      ok: false,
      error: "Project mismatch. Retry only against the originating project.",
    });
  }

  const retryApplied = [];
  const retryFailed = [];
  const retryAborted = [];
  for (const item of failed) {
    const match = plan.files.find((f) => f.id === item.id || f.path === item.path);
    if (!match) continue;
    const priorFailure = item?.test?.output || "";
    if (isTooComplexForSafeRetry(match.path, match.content, priorFailure)) {
      retryAborted.push({
        id: match.id,
        path: match.path,
        reason: complexityRecommendation(match.path),
      });
      continue;
    }
    const fallbackContent = buildRetryContent(match.path, match.content);
    const result = applyOneChangeWithRollback(
      { path: match.path, content: fallbackContent },
      plan.root,
      testCommand,
    );
    if (result.kept) {
      retryApplied.push({ id: match.id, path: match.path, test: result.testResult });
      match.content = fallbackContent;
    } else {
      retryFailed.push({ id: match.id, path: match.path, test: result.testResult });
    }
  }

  savePlans(plans);
  const retryReport = aiRetryNarrative(plan.metadata.featureTitle, retryApplied, retryFailed);
  const abortLines = retryAborted.map((x) => `- ${x.path}: ${x.reason}`).join("\n");
  const policyNote = retryAborted.length
    ? `\n\nAborted by complexity policy:\n${abortLines}`
    : "";
  pushHistory({
    timestamp: new Date().toISOString(),
    featureTitle: `${plan.metadata.featureTitle} (retry)`,
    summary: "Automatic fallback retry for failed files",
    projectPath: plan.root,
    projectKey: actualProjectKey,
    dryRun: false,
    featureClass: plan.featureClass,
    changeCount: retryApplied.length + retryFailed.length,
    status: retryFailed.length > 0 ? "retry-partial" : "retry-success",
  });

  return res.json({
    ok: true,
    projectPath: plan.root,
    retryApplied,
    retryFailed,
    retryAborted,
    retryReport: `${retryReport}${policyNote}`,
  });
});

app.get("/api/history", (_req, res) => {
  const projectKey = _req.query.projectKey;
  const all = getHistory();
  const filtered = projectKey ? all.filter((x) => x.projectKey === projectKey) : all;
  return res.json({ ok: true, history: filtered });
});

app.post("/api/latest-versions", (_req, res) => {
  return res.json({
    minecraftVersion: "1.20.1",
    neoForgeVersion: "20.6.130",
    createVersion: "LATEST",
    note: "Pin exact Create version in gradle.properties for strict pack reproducibility.",
  });
});

app.listen(PORT, () => {
  console.log(`Feature UI running on http://localhost:${PORT}`);
});
